import { Button, Col, Form, Input, Row } from "antd";
import Head from "next/head";
import Image from "next/image";
import React, { useState } from "react";
require("./index.less");

export default function Home() {
  const [domainUrl, setDomainUrl] = useState("");
  const [form] = Form.useForm();

  
  return (
    <div className="container">
      <Head>
        <title>Multi-Host</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="main">
        <h1 className="title">Welcome to Multi-Host! </h1>

        <div className="domain-section">
          <Form form={form}>
            <Row className="" style={{}}>
              <Col span={9} offset={6}>
                <Form.Item name="domain_url" rules={[{ required: true }]}>
                  <Input onChange={(e) => setDomainUrl(e.target.value)} />
                </Form.Item>
              </Col>
              <Col span={9}>
                <Button type="primary" size="middle" className=" mx-3">
                  HOST
                </Button>
              </Col>
            </Row>
          </Form>
        </div>

        <div className="grid">
          <a href="/" className="card" style={{ color: "black" }}>
            <h2>Deploy &rarr;</h2>
          </a>
        </div>
      </main>

      <footer className="footer">
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by INTELLIMEDIA
        </a>
      </footer>
    </div>
  );
}
