import { Button, Col, Form, Input, message, Row } from "antd";
import Head from "next/head";
import Image from "next/image";
import React, { useState, useEffect } from "react";
import axios from "axios";
require("./index.less");

export default function Home() {
  const [domainUrl, setDomainUrl] = useState("");
  const [address, setAddress] = useState(null);
  const [isCheckingHost, setIsCheckingHost] = useState(false);
  const [form] = Form.useForm();

  const addDomainhandler = (domain_url) => {
    const body = {
      domain_url: domain_url,
    };
    setIsCheckingHost(true);
    const url = `/api/checkhost`;
    axios
      .post(url, body)
      .then((response) => {
        console.log(response.data);
        if (response.data) {
          setAddress(response.data.name);
        } else {
          message.error("Domain doesn't exist");
        }
        setIsCheckingHost(false);
      })
      .catch((error) => {
        console.log(error);
        setIsCheckingHost(false);
      });
  };

  const updateConfig=(domainurl)=>{
    const url = `/api/getConfig`;
    axios
      .get(domainurl)
      .then((response) => {
        console.log(response);
      })
      .catch((error) => {
        console.log(error);
      });
  }
  useEffect(() => {
    if (domainUrl) {
      addDomainhandler(domainUrl);
    }
  }, [domainUrl]);
  return (
    <div className="container">
      <Head>
        <title>Multi-Host</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="main">
        <h1 className="title">Welcome to Multi-Host! </h1>

        <div className="domain-section">
          <Form form={form}>
            <Row className="" style={{}}>
              <Col span={14} offset={5}>
                <Form.Item name="domain_url" rules={[{ required: true }]}>
                  <Input
                    onChange={(e) => setDomainUrl(e.target.value)}
                    placeholder="Enter site-url, that you wanna host on your domain"
                  />
                </Form.Item>
              </Col>
              {/*<Col span={9}>
                <Button
                  type="primary"
                  size="middle"
                  className=" mx-3"
                  onClick={() => addDomainhandler(domainUrl)}
                  loading={isCheckingHost}
                >
                  HOST
                </Button>
              </Col>*/}
              {!isCheckingHost && address && (
                <div
                  className="h6 text-success text-center"
                  style={{ width: "100%" }}
                >
                  Address is :
                  <mark className="text-lead text-underline">{address}</mark>
                </div>
              )}
            </Row>
          </Form>
        </div>

        <div className="grid">
          <Button
            disabled={!address}
            className="card d-flex align-items-center justify-content-center"
            size="large"
            style={{ color: "black" }}
            onClick={()=>updateConfig(domainUrl)}
          >
            Deploy &rarr;
          </Button>
        </div>
      </main>

      <footer className="footer">
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by INTELLIMEDIA
        </a>
      </footer>
    </div>
  );
}
