import React from "react";
import Head from "next/head";

import styles from "./index.module.css";

export default function Home() {
  return (
    <div >
      <Head>
        <title>Next on Fly</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
  
      <div className={styles.main}>
        <section className={styles["description-section"]}>
          <div>
            <h1 className="hightlight-container">
              <span className="hightlight-text">
                Deploy sample next application on Fly.io
              </span>
            </h1>
          </div>
        </section>
      </div>
    </div>
  );
}
